import type { Metadata } from 'next'
// import { Inter } from "next/font/google";
import './globals.css'

// const inter = Inter({ subsets: ["latin"] });
import AuthContext from './ui/signin/authcontext'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="">
        <AuthContext>{children}</AuthContext>
      </body>
      <script src="https://apis.google.com/js/platform.js" async defer></script>
    </html>
  )
}
